/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SummerKatherine' at '8/30/17 1:56 PM' with Gradle 2.14.1
 *
 * @author SummerKatherine, @date 8/30/17 1:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
